/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const OnboardingAnswers = IDL.Record({
  'whatMattersMost' : IDL.Text,
  'timeSpentInstead' : IDL.Text,
  'explanation' : IDL.Text,
  'uncomfortableTruth' : IDL.Text,
});
export const Data = IDL.Record({
  'sentence' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOnboardingAnswers' : IDL.Func(
      [],
      [IDL.Opt(OnboardingAnswers)],
      ['query'],
    ),
  'getOnboardingStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'getReflectionState' : IDL.Func(
      [],
      [
        IDL.Record({
          'dailyReflectionDue' : IDL.Bool,
          'weeklyReflectionDue' : IDL.Bool,
        }),
      ],
      ['query'],
    ),
  'getSentenceHistory' : IDL.Func([], [IDL.Vec(Data)], ['query']),
  'getSentenceRetentionLimit' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeOnboarding' : IDL.Func([OnboardingAnswers], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logDailyReflection' : IDL.Func([IDL.Text], [], []),
  'logWeeklyReflection' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateOnboardingAnswers' : IDL.Func([OnboardingAnswers], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const OnboardingAnswers = IDL.Record({
    'whatMattersMost' : IDL.Text,
    'timeSpentInstead' : IDL.Text,
    'explanation' : IDL.Text,
    'uncomfortableTruth' : IDL.Text,
  });
  const Data = IDL.Record({ 'sentence' : IDL.Text, 'timestamp' : IDL.Int });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOnboardingAnswers' : IDL.Func(
        [],
        [IDL.Opt(OnboardingAnswers)],
        ['query'],
      ),
    'getOnboardingStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'getReflectionState' : IDL.Func(
        [],
        [
          IDL.Record({
            'dailyReflectionDue' : IDL.Bool,
            'weeklyReflectionDue' : IDL.Bool,
          }),
        ],
        ['query'],
      ),
    'getSentenceHistory' : IDL.Func([], [IDL.Vec(Data)], ['query']),
    'getSentenceRetentionLimit' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeOnboarding' : IDL.Func([OnboardingAnswers], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logDailyReflection' : IDL.Func([IDL.Text], [], []),
    'logWeeklyReflection' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateOnboardingAnswers' : IDL.Func([OnboardingAnswers], [], []),
  });
};

export const init = ({ IDL }) => { return []; };